### ISSUE TITLE
apply is not defined

### ISSUE THREAD

**Issue by Krulvis** [pymedia/pymedia#1]
getting error when trying to install this on python 3.7

`$ python setup.py build`
````Using UNIX configuration...

Continue building pymedia ? [Y,n]:y
Traceback (most recent call last):
  File "setup.py", line 314, in <module>
    apply(setup, [], PACKAGEDATA)
NameError: name 'apply' is not defined
````

**Comment by itsDevKay** [comment]
Have you gotten past this at any point? I've currently run into the same error. It doesn't seem to work even if you comment it out.

**Comment by Krulvis** [comment]
> Have you gotten past this at any point? I've currently run into the same error. It doesn't seem to work even if you comment it out.

Wow lol I have absolutely no idea what I needed this for. Let alone whether or not I fixed this issue :P
